version: '3.5'
services:
  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - './database:/data/db'
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
    ports:
      - '4200:4200'
  backend:
    build:
      context: ./server
      dockerfile: dev.dockerfile
    ports:
      - "2700:2700"
      - "2701:2701"
    depends_on:
      - database
    links:
      - database
    volumes:
      - '.:/app'
    environment:
      WAIT_HOSTS: database:27017

