version: '3.5'
services:
  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - './database:/data/db'
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
    ports:
      - '4200:4200'
  backend:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    environment:
      WAIT_HOSTS: database:27017

