version: '3.5'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
    ports:
      - '4200:4200'
  backend:
    build:
      context: ./server
      dockerfile: int.dockerfile
    ports:
      - "2700:2700"
      - "2701:2701"
    volumes:
      - '.:/app'

